var a = 20;
let b="abc";
const c=45;
console.log("Before redeclaration:",a);
console.log("Before redeclaration:",b);
console.log("Before redeclaration:",c);
a="xyz";
b=30;
//c=50;
console.log("After redeclaration:",a);
console.log("After redeclaration:",b);
//console.log("After redeclaration:",c);